# Generated by Django 4.2.3 on 2023-07-15 17:59

from django.db import migrations

def populate_team(apps, schemaeditor):
    entries = {
        "alpha": "This is the team Alpha",
        "bravo": "This is the team Bravo",
        "charlie": "This is the team Charlie",
        "delta": "This is the team Delta",
    }
    Team = apps.get_model("accounts", "Team")
    for name, desc in entries.items():
        team_obj = Team(name=name, description=desc)
        team_obj.save()

def populate_role(apps, schemaeditor):
    entries = {
        "Developer": "This is a Developer role",
        "Scrum Master": "This is a Scrum Master role",
        "Product Owner": "This is a Product Owner role"
    }
    Role = apps.get_model("accounts", "Role")
    for name, desc in entries.items():
        role_obj = Role(name=name, description=desc)
        role_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_team),
        migrations.RunPython(populate_role)
    ]
